import { Link } from 'react-router-dom';
import { Logo } from '../components/Logo';

const LAST_UPDATED = 'September 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 19, fontWeight: 600, letterSpacing: '-0.01em', color: 'var(--color-ink)', marginBottom: 12, paddingBottom: 10, borderBottom: '1px solid var(--color-dust)' }}>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {children}
      </div>
    </section>
  );
}

export function TermsPage() {
  return (
    <div style={{ minHeight: '100dvh', backgroundColor: 'var(--color-canvas)' }}>
      <nav className="nav-pill" role="navigation">
        <Link to="/" style={{ textDecoration: 'none', flexShrink: 0 }}>
          <Logo size={32} variant="full" dark={false} />
        </Link>
        <div style={{ flex: 1 }} />
        <Link to="/" className="btn-secondary" style={{ fontSize: 14, padding: '8px 18px' }}>← Back to home</Link>
      </nav>

      <main style={{
        paddingTop: 'calc(14px + 58px + 48px)',
        paddingBottom: 96,
        paddingLeft: 'clamp(16px, 6vw, 64px)',
        paddingRight: 'clamp(16px, 6vw, 64px)',
        maxWidth: 760, margin: '0 auto',
      }}>
        <p className="eyebrow" style={{ marginBottom: 14 }}>Legal</p>
        <h1 className="text-section" style={{ marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: 'var(--color-slate)', marginBottom: 48 }}>Last updated: {LAST_UPDATED}</p>

        <Section title="Agreement to Terms">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            By accessing or using FeeLedger (available at feeledger.github.io), you agree to be bound by these
            Terms of Service. If you do not agree to these terms, please do not use the application.
          </p>
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            FeeLedger is a free, open-source application provided as-is. It is not operated as a commercial
            service and has no associated company, subscription, or commercial entity.
          </p>
        </Section>

        <Section title="What FeeLedger Is">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            FeeLedger is a static web application that runs entirely in your browser. It helps tutors, coaching
            centres, and small businesses manage student records, record fee payments, and generate receipts.
          </p>
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            All data you enter is stored in your own Google Drive account. FeeLedger has no servers,
            no databases, and no access to your data beyond what you explicitly authorise through Google's
            permission system.
          </p>
        </Section>

        <Section title="Use of the Application">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>You agree to use FeeLedger only for lawful purposes. You must not:</p>
          <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
            {[
              'Use the application to store or process data in violation of applicable laws',
              'Attempt to reverse-engineer, modify, or distribute modified versions without complying with the MIT Licence',
              'Use the application in a way that infringes on the rights of others',
              'Misrepresent receipts or financial records generated by the application',
            ].map(item => (
              <li key={item} style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.7 }}>{item}</li>
            ))}
          </ul>
        </Section>

        <Section title="Your Data and Responsibility">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            Because all data is stored in your own Google Drive, you are solely responsible for the data you
            enter, maintain, and manage. FeeLedger cannot access, backup, recover, or be held responsible for
            any data you store or lose.
          </p>
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            You are responsible for ensuring that your use of student or member data complies with applicable
            privacy laws in your jurisdiction (such as the Information Technology Act, GDPR, or similar
            legislation as applicable).
          </p>
        </Section>

        <Section title="Receipts and Financial Records">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            FeeLedger generates payment receipts based on the information you enter. The accuracy and
            completeness of these receipts is entirely your responsibility. FeeLedger makes no representations
            about whether receipts generated comply with any particular tax, accounting, or legal requirements
            in your jurisdiction.
          </p>
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            If you use FeeLedger for GST invoicing or tax-related purposes, you are responsible for ensuring
            compliance with applicable tax laws. Consult a qualified accountant or tax professional for advice.
          </p>
        </Section>

        <Section title="Google Account and OAuth">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            FeeLedger uses Google's OAuth 2.0 system for sign-in and Google Drive access. By signing in, you
            grant FeeLedger the specific permissions listed during the consent screen — currently
            <code style={{ background: 'var(--color-bone)', padding: '1px 6px', borderRadius: 4, fontSize: 13 }}> drive.file</code> scope
            (access only to files FeeLedger creates) and basic profile information.
          </p>
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            You can revoke these permissions at any time by visiting{' '}
            <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--color-link)' }}>
              myaccount.google.com/permissions
            </a>.
          </p>
        </Section>

        <Section title="Data Deletion">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            You can delete all your FeeLedger data at any time by:
          </p>
          <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
            <li style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.7 }}>
              Using Settings → Account → Delete All Data within the application
            </li>
            <li style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.7 }}>
              Manually deleting the <strong>FeeLedger</strong> folder from your Google Drive
            </li>
            <li style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.7 }}>
              Revoking Google account access at myaccount.google.com/permissions
            </li>
          </ul>
        </Section>

        <Section title="Open Source Licence">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            FeeLedger is open source software released under the{' '}
            <a href="https://github.com/feeledger/feeledger.github.io/blob/main/LICENSE"
               target="_blank" rel="noopener noreferrer" style={{ color: 'var(--color-link)' }}>
              MIT Licence
            </a>.
            You are free to fork, modify, and distribute the code subject to the terms of that licence.
            The MIT Licence permits commercial use, modification, distribution, and private use.
          </p>
        </Section>

        <Section title="Disclaimer of Warranties">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            FeeLedger is provided "as is" and "as available" without warranties of any kind, express or implied.
            We do not warrant that the application will be error-free, uninterrupted, or meet your specific requirements.
          </p>
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            In particular, we make no warranty regarding the accuracy of financial calculations, the suitability
            of generated receipts for legal or tax purposes, or the availability of the application.
          </p>
        </Section>

        <Section title="Limitation of Liability">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            To the maximum extent permitted by applicable law, the contributors to FeeLedger shall not be
            liable for any indirect, incidental, special, consequential, or punitive damages, including but
            not limited to loss of data, loss of revenue, or loss of goodwill, arising from your use of the
            application.
          </p>
        </Section>

        <Section title="Changes to These Terms">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            These terms may be updated from time to time. The updated version will be posted at this URL with
            a revised date. Continued use of the application after changes constitutes acceptance of the new terms.
          </p>
        </Section>

        <Section title="Contact">
          <p style={{ fontSize: 15, color: 'var(--color-charcoal)', lineHeight: 1.75 }}>
            Questions about these terms can be raised by opening an issue at{' '}
            <a href="https://github.com/feeledger/feeledger.github.io/issues"
               target="_blank" rel="noopener noreferrer" style={{ color: 'var(--color-link)' }}>
              github.com/feeledger/feeledger.github.io/issues
            </a>.
          </p>
        </Section>

        <div style={{ marginTop: 48, padding: 24, background: 'var(--color-lifted)', borderRadius: 20, border: '1px solid var(--color-dust)' }}>
          <p style={{ fontSize: 14, color: 'var(--color-slate)', lineHeight: 1.7 }}>
            <strong style={{ color: 'var(--color-ink)' }}>Plain English summary:</strong>{' '}
            FeeLedger is a free tool. Your data is yours. We have no servers. Use it responsibly.
            We are not liable if something goes wrong. The code is MIT-licensed — use it however you like.
          </p>
        </div>
      </main>

      <footer className="footer" style={{ padding: 'clamp(24px,4vw,40px) clamp(16px,4vw,48px)' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <Logo size={24} variant="full" dark={true} />
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <Link to="/privacy" style={{ color: 'var(--color-slate)', fontSize: 13, textDecoration: 'none' }}>Privacy Policy</Link>
            <Link to="/terms"   style={{ color: 'var(--color-slate)', fontSize: 13, textDecoration: 'none' }}>Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

import React from 'react';
